kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: docker/compose
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker-compose up -d

volumes:
  - name: docker_socket
    path: /var/run/docker.sock
