kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: docker/compose:debian
    commands:
      - echo /bin -la --color
#      - sh ./.drone/deploy.sh
#      - sh ./.drone/test.sh
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock