kind: pipeline
name: cicd

steps:
  - name: test
    image: docker/compose
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - pwd
      - ls -la
      - docker-compose up -f /drone/src/docker-compose.yaml