kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: docker/compose
    commands:
      - sh ./.drone/deploy.sh
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker_socket
    path: /var/run/docker.sock
