controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

base:
    path: /
    controller: App\Controller\MyController::base

index:
    path: /index
    controller: App\Controller\MyController::index