controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

base:
    path: /
    controller: App\Controller\MyController::base

index:
    path: /index
    controller: App\Controller\MyController::index

ads_back_index:
    path: /ads
    controller: App\Controller\AdsController::index

ads_back_show:
    path: /ads/show
    controller: App\Controller\AdsController::show