controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

base:
    path: /
    controller: App\Controller\MyController::base

index:
    path: /index
    controller: App\Controller\MyController::index

ads_back_index:
    path: /ad
    controller: App\Controller\AdController::index

ads_back_show:
    path: /ad/show
    controller: App\Controller\AdController::show