name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    environment: CI-CD-test
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      TARGET: "/home/root/www"
      EXCLUDE: "/.gitignore, /README.md"

    runs-on: ubuntu-latest
    steps:
    - name: Choppe moi le code
      uses: actions/checkout@v1

    - name: Deploie moi ça gros sagouin
      uses: easingthemes/ssh-deploy@main

    - name: Recree le docker stp
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ env.TARGET }}
          docker-compose stop
          docker-compose rm
          docker-compose up -d
          docker ps
